config/routes.rb
TennerDeals::Application.routes.draw do
  get "admin/index"
  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :admin_users

  resources :newsletters

  resources :orders

  resources :line_items

  resources :carts

  get "bob/index"
  get "bob/show"
  get "fitness/index"
  get "fitness/show"
  get "soon/index"
  get "soon/show"
  get "student/index"
  get "student/show"
  get "lunch/index"
  get "lunch/show"
  get "home/index"
  get "home/show"
  resources :deals

  root 'home#index', as: 'home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  validates :name, presence: true
  has_secure_password
end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :line_items, dependent: :destroy

def add_deal(deal_id) 
   current_item = line_items.find_by(deal_id: deal_id) 
   if current_item
   current_item.quantity += 1 
      else 
	  current_item = line_items.build(deal_id: deal_id) 
	end 
	current_item 
  end
def total_price
    line_items.to_a.sum { |item| item.total_price }
end
end

app/models/deal.rb
class Deal < ActiveRecord::Base
has_many :line_items
has_many :orders, through: :line_items
before_destroy :ensure_not_referenced_by_any_line_item


CATEGORY = [ "Lunch", "Student Deal", "Coming Soon", "Fitness" ]
STATUS = [ "Valid", "Not Valid", "Deal Used", "Sold Out" ]
#todo need to add validation for deal table

#Geocoder
geocoded_by :address
after_validation :geocode

#Paperclip gem
validates :photo, presence: false

has_attached_file :photo, 
                  :url => "/app/assets/images/:filename",
				  :path => ":rails_root/app/assets/images/:filename",
				  :default_url => "/images/:style/missing.png"

				  
	  def self.latest
   Deal.order(:updated_at).last 
   end
		private
   def ensure_not_referenced_by_any_line_item 
    if line_items.empty?
   return true
   else errors.add(:base, 'Line Items present') 
    return false
  end 
end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :deal
  belongs_to :cart
  
  def total_price
  deal.price * quantity
end
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
 #attr_accessible :name
end

app/models/order.rb
class Order < ActiveRecord::Base
has_many :line_items, dependent: :destroy
GENDER = [ "Male", "Female" ]
STATUS = [ "VALID", "DEAL USED", "DEAL OUT OF DATE", "DEAL VOID" ]
PAYMENT_TYPES = [ "Visa", "Master Card", "Laser", "American Express" ]

#Geocoder
geocoded_by :address
after_validation :geocode


def add_line_items_from_cart(cart)
 cart.line_items.each do |item|
 item.cart_id = nil
 line_items << item
 end
end

end

app/controllers/bob_controller.rb
class BobController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
   skip_before_action :authorize, only: [:new, :create, :show, :update, :destroy]

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all
	 # redirect_to home_url, notice: "Logged out"

  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
    #added code to get rid of no method nill class error
    @newsletter = Newsletter.find(params[:id])
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
	    
end
  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
	  PurchasedDeal.welcome_email(@newsletter).deliver
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @newsletter }
      else
        format.html { render action: 'new' }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to home_url, notice: 'Newsletter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json #changed code params id
  def destroy
    @newsletter = Newsletter.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to newsletters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id]) 
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:name, :email, :agree)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def hidden_div_if(condition, attributes = {}, &block)
 if condition
 attributes["style"] = "display: none"
 end
 content_tag("div", attributes, &block)
end
end

app/helpers/bob_helper.rb
module BobHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/fitness_helper.rb
module FitnessHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/lunch_helper.rb
module LunchHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/soon_helper.rb
module SoonHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/newsletters/_form.html.erb
<%= form_for(@newsletter) do |f| %>
  <% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% @newsletter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label 'I want to recieve newsletter' %><br>
    <%= f.check_box :agree %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<h1>Editing newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<h1>Listing newsletters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Agree</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @newsletters.each do |newsletter| %>
      <tr>
        <td><%= newsletter.name %></td>
        <td><%= newsletter.email %></td>
        <td><%= newsletter.agree %></td>
        <td><%= link_to 'Show', newsletter %></td>
        <td><%= link_to 'Edit', edit_newsletter_path(newsletter) %></td>
        <td><%= link_to 'Destroy', newsletter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsletter', new_newsletter_path %>

app/views/newsletters/new.html.erb
<h1>New newsletter</h1>

<%= render 'form' %>

<%= link_to 'Back', newsletters_path %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @newsletter.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @newsletter.email %>
</p>

<p>
  <strong>Agree:</strong>
  <%= @newsletter.agree %>
</p>

<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>