config/routes.rb
TennerDeals::Application.routes.draw do
  get "admin/index"
  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :admin_users

  resources :newsletters

  resources :orders

  resources :line_items

  resources :carts

  get "bob/index"
  get "bob/show"
  get "fitness/index"
  get "fitness/show"
  get "soon/index"
  get "soon/show"
  get "student/index"
  get "student/show"
  get "lunch/index"
  get "lunch/show"
  get "home/index"
  get "home/show"
  resources :deals

  root 'home#index', as: 'home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  validates :name, presence: true
  has_secure_password
end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :line_items, dependent: :destroy

def add_deal(deal_id) 
   current_item = line_items.find_by(deal_id: deal_id) 
   if current_item
   current_item.quantity += 1 
      else 
	  current_item = line_items.build(deal_id: deal_id) 
	end 
	current_item 
  end
def total_price
    line_items.to_a.sum { |item| item.total_price }
end
end

app/models/deal.rb
class Deal < ActiveRecord::Base
has_many :line_items
has_many :orders, through: :line_items
before_destroy :ensure_not_referenced_by_any_line_item


CATEGORY = [ "Lunch", "Student Deal", "Coming Soon", "Fitness" ]
STATUS = [ "Valid", "Not Valid", "Deal Used", "Sold Out" ]
#todo need to add validation for deal table

#Geocoder
geocoded_by :address
after_validation :geocode

#Paperclip gem
validates :photo, presence: false

has_attached_file :photo, 
                  :url => "/app/assets/images/:filename",
				  :path => ":rails_root/app/assets/images/:filename",
				  :default_url => "/images/:style/missing.png"

				  
	  def self.latest
   Deal.order(:updated_at).last 
   end
		private
   def ensure_not_referenced_by_any_line_item 
    if line_items.empty?
   return true
   else errors.add(:base, 'Line Items present') 
    return false
  end 
end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :deal
  belongs_to :cart
  
  def total_price
  deal.price * quantity
end
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
 #attr_accessible :name
end

app/models/order.rb
class Order < ActiveRecord::Base
has_many :line_items, dependent: :destroy
GENDER = [ "Male", "Female" ]
STATUS = [ "VALID", "DEAL USED", "DEAL OUT OF DATE", "DEAL VOID" ]
PAYMENT_TYPES = [ "Visa", "Master Card", "Laser", "American Express" ]

#Geocoder
geocoded_by :address
after_validation :geocode


def add_line_items_from_cart(cart)
 cart.line_items.each do |item|
 item.cart_id = nil
 line_items << item
 end
end

end

app/controllers/bob_controller.rb
class BobController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
   skip_before_action :authorize, only: [:show, :view]
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  @deals = Deal.all
  end
 # def percentSaved(otherDeal)
#(otherDeal.priceofdeal - priceofdeal)/otherDeal.priceofdeal * 100
#end


  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @deal }
      else
        format.html { render action: 'new' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:name, :category, :description, :image_url, :price, :value, :address, :latitude, :longitude, :status, :terms, :photo)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def hidden_div_if(condition, attributes = {}, &block)
 if condition
 attributes["style"] = "display: none"
 end
 content_tag("div", attributes, &block)
end
end

app/helpers/bob_helper.rb
module BobHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/fitness_helper.rb
module FitnessHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/lunch_helper.rb
module LunchHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/soon_helper.rb
module SoonHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/deals/_form.html.erb
<%= form_for(@deal, :html => { :multipart => true }) do |f| %>

  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, Deal::CATEGORY,
                  prompt: 'Select Deal Category' %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
  <%= f.file_field :photo %>
   </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address, :rows => 3, :cols => 40 %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, Deal::STATUS,
 prompt: 'Select deal status' %>
  </div>
  
  
 
  <div class="field">
    <%= f.label :terms %><br>
    <%= f.text_area :terms, rows: 8 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<h1>Listing Deals</h1>

<table> 
<% @deals.each do |deal| %> 
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
<td> <%= image_tag(deal.image_url, class: 'list_image') %> </td> 
<td class="list_description"> 
<dl> 
<dt><%= deal.name %></dt> 
<dd><%= truncate(strip_tags(deal.description), length: 80) %></dd>
 </dl> 
 </td> 
 <td class="list_actions"> 
 <%= link_to 'Show', deal %><br/> 
 <%= link_to 'Edit', edit_deal_path(deal) %><br/> 
 <%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %> </br>
 <%= link_to 'New Deal', new_deal_path %>

 </td> 
 </tr>
 <% end %> 
 </table> <br />
 <div id="BOB" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
 
 <script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>
 <script type="text/javascript">
$(function () {
        $('#BOB').highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: 'Total Deal Types'
            },
            subtitle: {
                text: 'Source: Db deals table'
            },
            xAxis: {
                categories: ['LUNCH', 'STUDENT', 'COMING SOON', 'FITNESS'],
                title: {
                    text: null
                }
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Total Number',
                    align: 'high'
                },
                labels: {
                    overflow: 'justify'
                }
            },
            tooltip: {
                valueSuffix: ''
            },
            plotOptions: {
                bar: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },

            credits: {
                enabled: false
            },
            series: [{
               name: 'Deal',
               data: [<%= Deal.where(:category => 'Lunch').count %>, <%= Deal.where(:category => 'Student Deal').count %>, 
			   <%= Deal.where(:category => 'Coming Soon').count %>, <%= Deal.where(:category => 'Fitness').count %>]
            }]
        });
    });
</script>

app/views/deals/new.html.erb
<h1>New deal</h1>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Bobbbbbbbbbyyyyyyyy</h1>
<h3>nearby Deals</h3>
<ul>
<% for deal in @deal.nearbys(10) %>
   <li><%= link_to deal.address, deal %>(<%= deal.distance.round(2) %> miles)</li>
<% end %>
</ul>

<p>
  <strong>Name:</strong>
  <%= @deal.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @deal.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @deal.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @deal.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @deal.price %>
</p>

<p>
  <strong>Value:</strong>
  <%= @deal.value %>
</p>

<p>
  <strong>Address:</strong>
  <%= @deal.address %>
</p>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@deal.latitude}%2C#{@deal.longitude}" %>

<p>
  <strong>Latitude:</strong>
  <%= @deal.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @deal.longitude %>
</p>

<p>
  <strong>Status:</strong>
  <%= @deal.status %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @deal.terms %>
</p>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>
<div id="until2d"></div>