config/routes.rb
TennerDeals::Application.routes.draw do
  get "admin/index"
  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :admin_users

  resources :newsletters

  resources :orders

  resources :line_items

  resources :carts

  get "bob/index"
  get "bob/show"
  get "fitness/index"
  get "fitness/show"
  get "soon/index"
  get "soon/show"
  get "student/index"
  get "student/show"
  get "lunch/index"
  get "lunch/show"
  get "home/index"
  get "home/show"
  resources :deals

  root 'home#index', as: 'home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  validates :name, presence: true
  has_secure_password
end

app/models/cart.rb
class Cart < ActiveRecord::Base
has_many :line_items, dependent: :destroy

def add_deal(deal_id) 
   current_item = line_items.find_by(deal_id: deal_id) 
   if current_item
   current_item.quantity += 1 
      else 
	  current_item = line_items.build(deal_id: deal_id) 
	end 
	current_item 
  end
def total_price
    line_items.to_a.sum { |item| item.total_price }
end
end

app/models/deal.rb
class Deal < ActiveRecord::Base
has_many :line_items
has_many :orders, through: :line_items
before_destroy :ensure_not_referenced_by_any_line_item


CATEGORY = [ "Lunch", "Student Deal", "Coming Soon", "Fitness" ]
STATUS = [ "Valid", "Not Valid", "Deal Used", "Sold Out" ]
#todo need to add validation for deal table

#Geocoder
geocoded_by :address
after_validation :geocode

#Paperclip gem
validates :photo, presence: false

has_attached_file :photo, 
                  :url => "/app/assets/images/:filename",
				  :path => ":rails_root/app/assets/images/:filename",
				  :default_url => "/images/:style/missing.png"

				  
	  def self.latest
   Deal.order(:updated_at).last 
   end
		private
   def ensure_not_referenced_by_any_line_item 
    if line_items.empty?
   return true
   else errors.add(:base, 'Line Items present') 
    return false
  end 
end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :deal
  belongs_to :cart
  
  def total_price
  deal.price * quantity
end
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
 #attr_accessible :name
end

app/models/order.rb
class Order < ActiveRecord::Base
has_many :line_items, dependent: :destroy
GENDER = [ "Male", "Female" ]
STATUS = [ "VALID", "DEAL USED", "DEAL OUT OF DATE", "DEAL VOID" ]
PAYMENT_TYPES = [ "Visa", "Master Card", "Laser", "American Express" ]

#Geocoder
geocoded_by :address
after_validation :geocode


def add_line_items_from_cart(cart)
 cart.line_items.each do |item|
 item.cart_id = nil
 line_items << item
 end
end

end

app/controllers/bob_controller.rb
class BobController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_action :authorize, only: :create
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    deal = Deal.find(params[:deal_id])
    @line_item = @cart.add_deal(deal.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to home_url }
		format.js   { @current_item = @line_item }
        format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:deal_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def hidden_div_if(condition, attributes = {}, &block)
 if condition
 attributes["style"] = "display: none"
 end
 content_tag("div", attributes, &block)
end
end

app/helpers/bob_helper.rb
module BobHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/fitness_helper.rb
module FitnessHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/lunch_helper.rb
module LunchHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/soon_helper.rb
module SoonHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deal_id %><br>
    <%= f.text_field :deal_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
 <tr id="current_item">
 <% else %>
<tr> 
<% end %>
<td><%= line_item.quantity %>&times;</td> 
<td><%= line_item.deal.name %></td>
<td class="item_price"><%= number_to_currency(line_item.total_price, :unit => "€") %></td> 
</tr> 

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
 line_item.quantity, 
 truncate(line_item.deal.name, length: 50)) %>

app/views/line_items/create.js.erb
$('#notice').hide();
if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }
$('#cart').html("<%= escape_javascript render(@cart) %>");

$('#current_item').css({'background-color':'#88ff88'}).
animate({'background-color':'#114411'}, 1000);

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Deal</th>
      <th>Cart</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.deal %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deal:</strong>
  <%= @line_item.deal %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>